### PR TITLE
add createFork createRepo deleteRepo hasRepo

### PR DESCRIPTION
**Pull request by Hazel0928**

### CODE REVIEW

**Comment by Hazel0928** [comment]
https://github.com/serverless-cd/serverless-cd/issues/19#issue-156071001
https://github.com/serverless-cd/serverless-cd/issues/20
https://github.com/serverless-cd/serverless-cd/issues/21

**Comment by Hazel0928** [comment]
#https://github.com/serverless-cd/serverless-cd/issues/21

**Review by heimanba — COMMENTED** [review]
LGTM

**Review by heimanba — COMMENTED** [review]
LGTM

**Comment by heimanba** [comment]
https://github.com/serverless-cd/serverless-cd/issues/21
https://github.com/serverless-cd/serverless-cd/issues/20
https://github.com/serverless-cd/serverless-cd/issues/19

**Pull request merged**
